cicd: qa: standardize the file
This commit removes the blank line and indentation the code.

Signed-off-by: Leonardo R.S. Joao <leonardo.joao@ossystems.com.br>

diff --git a/.github/workflows/qa.yml b/.github/workflows/qa.yml
--- a/.github/workflows/qa.yml
+++ b/.github/workflows/qa.yml
@@ -10,7 +10,6 @@ on:
 
 
 jobs:
-
   validate:
     name: validate
     if: ${{ github.event.pull_request.draft == false }}
@@ -42,100 +41,99 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Check out code
+        uses: actions/checkout@v2
 
-    - name: Check out code
-      uses: actions/checkout@v2
+      - uses: dorny/paths-filter@v2.2.0
+        id: filter
+        with:
+          # inline YAML or path to separate file (e.g.: .github/filters.yaml)
+          filters: |
+            ui:
+              - 'ui/**'
+            go:
+              - 'api/**'
+              - 'agent/**'
+              - 'pkg/**'
+              - 'ssh/**'
+              - 'cli/**'
 
-    - uses: dorny/paths-filter@v2.2.0
-      id: filter
-      with:
-        # inline YAML or path to separate file (e.g.: .github/filters.yaml)
-        filters: |
-          ui:
-            - 'ui/**'
-          go:
-            - 'api/**'
-            - 'agent/**'
-            - 'pkg/**'
-            - 'ssh/**'
-            - 'cli/**'
+      - name: Set up Go 1.x [Go]
+        if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
+        uses: actions/setup-go@v2
+        with:
+          go-version: 1.16
+        id: go
 
-    - name: Set up Go 1.x [Go]
-      if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
-      uses: actions/setup-go@v2
-      with:
-        go-version: 1.16
-      id: go
+      - name: Cache Go files [Go]
+        uses: actions/cache@v1
+        if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
+        with:
+          path: ~/go/pkg/mod
+          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
 
-    - name: Cache Go files [Go]
-      uses: actions/cache@v1
-      if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
-      with:
-        path: ~/go/pkg/mod
-        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
-
-    - name: Get Go dependencies [Go]
-      if: matrix.project != 'ui' && github.event.pull_request.draft == false
-      working-directory: ${{ matrix.project }}
-      run: go mod download
-
-    - name: Ensure Go dependencies are complete [Go]
-      if: matrix.project != 'ui' &&  github.event.pull_request.draft == false
-      working-directory: ${{ matrix.project }}
-      run: |
-        go mod tidy
-        if [ -n "$(git status --porcelain)" ]; then
-            echo "Missing dependencies on 'go.mod'"
-            exit 1
-        fi
-
-    - name: Unit test [Go]
-      if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
-      working-directory: ${{ matrix.project }}
-      run: go test -v ${{ matrix.extra_args }} ./...
-
-    - name: Go build [Go]
-      if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
-      working-directory: ${{ matrix.project }}
-      run: go build -v ${{ matrix.extra_args }} ./...
-
-    - name: Code format [Go]
-      run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
-      if: matrix.os == 'ubuntu-latest' && github.event.pull_request.draft == false
-
-    - name: Code linting [Go]
-      if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
-      uses: golangci/golangci-lint-action@v2
-      with:
+      - name: Get Go dependencies [Go]
+        if: matrix.project != 'ui' && github.event.pull_request.draft == false
         working-directory: ${{ matrix.project }}
-        version: v1.37
-        args: ${{ matrix.lint_args }}
-        skip-pkg-cache: true
+        run: go mod download
 
-    - name: Set up Node.JS 15.14 [UI]
-      if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
-      uses: actions/setup-node@v1
-      with:
+      - name: Ensure Go dependencies are complete [Go]
+        if: matrix.project != 'ui' &&  github.event.pull_request.draft == false
+        working-directory: ${{ matrix.project }}
+        run: |
+          go mod tidy
+          if [ -n "$(git status --porcelain)" ]; then
+              echo "Missing dependencies on 'go.mod'"
+              exit 1
+          fi
+
+      - name: Unit test [Go]
+        if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
+        working-directory: ${{ matrix.project }}
+        run: go test -v ${{ matrix.extra_args }} ./...
+
+      - name: Go build [Go]
+        if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
+        working-directory: ${{ matrix.project }}
+        run: go build -v ${{ matrix.extra_args }} ./...
+
+      - name: Code format [Go]
+        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi
+        if: matrix.os == 'ubuntu-latest' && github.event.pull_request.draft == false
+
+      - name: Code linting [Go]
+        if: matrix.project != 'ui' && steps.filter.outputs.go == 'true' && github.event.pull_request.draft == false
+        uses: golangci/golangci-lint-action@v2
+        with:
+          working-directory: ${{ matrix.project }}
+          version: v1.37
+          args: ${{ matrix.lint_args }}
+          skip-pkg-cache: true
+
+      - name: Set up Node.JS 15.14 [UI]
+        if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
+        uses: actions/setup-node@v1
+        with:
           node-version: "15.14"
 
-    - name: Cache node modules [UI]
-      if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
-      uses: actions/cache@v1
-      with:
-        path: ui/node_modules
-        key: ${{ runner.OS }}-ui-${{ hashFiles('**/package-lock.json') }}
+      - name: Cache node modules [UI]
+        if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
+        uses: actions/cache@v1
+        with:
+          path: ui/node_modules
+          key: ${{ runner.OS }}-ui-${{ hashFiles('**/package-lock.json') }}
 
-    - name: Install Node Dependencies [UI]
-      if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
-      working-directory: ${{ matrix.project }}
-      run: npm install
+      - name: Install Node Dependencies [UI]
+        if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
+        working-directory: ${{ matrix.project }}
+        run: npm install
 
-    - name: Unit test [UI]
-      if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
-      working-directory: ${{ matrix.project }}
-      run: npm run test:unit -- -u
+      - name: Unit test [UI]
+        if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
+        working-directory: ${{ matrix.project }}
+        run: npm run test:unit -- -u
 
-    - name: Save Code Linting Report JSON [UI]
-      if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
-      working-directory: ${{ matrix.project }}
-      run: npm run lint:no-fix
+      - name: Save Code Linting Report JSON [UI]
+        if: matrix.project == 'ui' && steps.filter.outputs.ui == 'true' && github.event.pull_request.draft == false
+        working-directory: ${{ matrix.project }}
+        run: npm run lint:no-fix
